from tkinter import *
root=Tk()
root.title("Login page")
root.geometry("500x500")
root.configure(bg="light green")
l1=Label(root,text="Name")
l2=Label(root,text="Branch")
l3=Label(root,text="Section")
l4=Label(root,text="Roll no")
l5=Label(root,text="Mobile")
l6=Label(root,text="Email")
l1.grid(row=0,column=0)
l2.grid(row=1,column=0)
l3.grid(row=2,column=0)
l4.grid(row=3,column=0)
l5.grid(row=4,column=0)
l6.grid(row=5,column=0)
e1=Entry(root)
e2=Entry(root)
e3=Entry(root)
e4=Entry(root)
e5=Entry(root)
e6=Entry(root)
e1.grid(row=0,column=1)
e2.grid(row=1,column=1)
e3.grid(row=2,column=1)
e4.grid(row=3,column=1)
e5.grid(row=4,column=1)
e6.grid(row=5,column=1)
def display():
    print("Name :",e1.get())
    print("Branch :",e2.get())
    print("Section :",e3.get())
    print("Roll no :",e4.get())
    print("Mobile :",e5.get())
    print("Email :",e6.get())
    with open("Collected details.txt","a") as fo:
        fo.write("Name: " + e1.get() + "\n")
        fo.write("Branch: " + e2.get() + "\n")
        fo.write("Section: " + e3.get() + "\n")
        fo.write("Roll no: " + e4.get() + "\n")
        fo.write("Mobile: " + e5.get() + "\n")
        fo.write("Email: " + e6.get() + "\n")
        fo.write("----------------------\n")
b=Button(root,text="submit",command=display)
b.grid(row=6,column=2)
mainloop()