from tkinter import *
root=Tk()
root.title("Form")
root.geometry("500x500")
l1=Label(root,text="Name")
l2=Label(root,text="Age")
l1.grid(row=0,column=0)
l1.configure(fg="Blue",font=("Times new roman",16,"bold"))
l2.grid(row=1,column=0)
l2.configure(fg="Blue",font=("Times new roman",16,"bold"))
e1=Entry(root)
e1.grid(row=0,column=1)
e2=Entry(root)
e2.grid(row=1,column=1)
def display():
    #a=e1.get()
    #b=e2.get()
    l.configure(text=f"Name : {e1.get()}\n Age : {e2.get()}")
b=Button(root,text="Submit",command=display)
b.grid(row=2,column=1)
l=Label(root,text=" ")
l.grid(row=3,column=1)
mainloop()