from tkinter import *
root=Tk()
root.title("Login page")
root.geometry("500x500")
root.configure(bg="Orange")
l1=Label(root,text="Username")
l2=Label(root,text="Password")
l1.grid(row=0,column=0)
l2.grid(row=1,column=0)
e1=Entry(root)
e2=Entry(root)
e1.grid(row=0,column=1)
e2.grid(row=1,column=1)
e2.config(show="*")
def login():
    print(" Welcome ",e1.get())
    if len(e2.get())>=8:
        r=Tk()
        r.title("Welcome")
        r.geometry("320x200")
        p=Label(r,text=f"Welcome {e1.get()}").pack(pady=50,padx=10)
        mainloop()
b=Button(root,text="Login",command=login)
b.grid(row=2,column=1)
mainloop()