from tkinter import *
root=Tk()
root.title("Login page")
root.geometry("500x500")
#root.configure(bg="Orange")
l1=Label(root,text="Username")
l2=Label(root,text="Password")
l1.grid(row=0,column=0)
l2.grid(row=1,column=0)
e1=Entry(root)
e2=Entry(root)
e1.grid(row=0,column=1)
e2.grid(row=1,column=1)
def login():
    print("Username :",e1.get())
    print("Password : ",e2.get())
b=Button(root,text="Login",command=login)
b.grid(row=2,column=1)
mainloop()