file=open("basic_details","w")
name=input("Enter name : ")
age=int(input("Enter age : "))
mobile=int(input("Mobile no : "))
email=input("Enter mail id : ")
file.write(f"Name :{name}\n")
file.write(f"Age :{str(age)}\n")
file.write(f"Mobile : {str(mobile)}\n")
file.write(f"Email : {email}\n")