from tkinter import *
r=Tk()
r.title("EVM")
r.geometry("500x500")
rv=StringVar(value="NOTA")
def vote():
    v=rv.get()
    l.configure(text=f"Your vote has been casted to {v}")
    #print(f"Your vote has been casted to {v}")
Radiobutton(r,text="CYCLE",variable=rv,value="Chandrababu naidu").pack()
Radiobutton(r,text="FAN",variable=rv,value="Jaganmohan Reddy").pack()
Radiobutton(r,text="NOTA",variable=rv,value="NOTA").pack()
b=Button(r,text="Submit",command=vote)
b.pack(pady=50)
l=Label(r,text=" ")
l.pack()
mainloop()